import { platform } from "os";

export const GENDER_OPTIONS = [
  { label: "Male", value: "Male" },
  { label: "Female", value: "Female" },
  { label: "Others", value: "Others" },
];

export const PRICING_OPTIONS = [
  {
    id: 1,
    name: "Free Tier",
    price: "₹0",
    yearly_price: "₹0",
    frequency: "Per Month ",
    free_events: "2 Free",
    publishing_pay: "₹250/event ",
    gst: "higher",
    payement_gst: "Ex : 1000 + ₹100(10%) Platform fee + ₹18 (18%) GST",
    total: "Total 1118 Per registration",
    invite_only: false,
    color: "text-[#FB7185]",
    bg: "bg-[#FB7185]",
  },
  {
    id: 2,
    name: "Pro Tier",
    price: "₹499",
    yearly_price: "₹4999",
    frequency: "Per Month ",
    free_events: "12 Free",
    publishing_pay: "₹150/event",
    gst: "lower",
    payement_gst: "Ex : 1000 + ₹50(10%) Platform fee + ₹9 (18%) GST",
    total: "Total 1059 Per registration",
    invite_only: false,
    color: "text-[#F4C01E]",
    bg: "bg-[#F4C01E]",
  },
  {
    id: 3,
    name: "Pro Plus Tier",
    price: "Yearly Plan Only",
    yearly_price: "₹14,999",
    frequency: "Per Month ",
    free_events: "Unlimited",
    publishing_pay: "₹0 - Always Free",
    gst: "lower",
    payement_gst: "Ex : 1000 + ₹50(10%) Platform fee + ₹9 (18%) GST",
    total: "Total 1059 Per registration",
    invite_only: true,
    color: "text-[#4EF162]",
    bg: "bg-[#4EF162]",
  },
];

export const PRICING_OPTIONS_COMPARISON = [
  {
    id: 1,
    feature: "Access to Player App Users",
    free_tier_text: "Required",
    pro_tier_text: "Required",
    pro_plus_tier_text: "Auto-arranged",
  },
  {
    id: 2,
    feature: "Publish Recurring Tournaments",
    free_tier: true,
    pro_tier: true,
    pro_plus_tier: true,
  },
  {
    id: 3,
    feature: "WhatsApp Notifications to Players",
    free_tier: "-",
    pro_tier: true,
    pro_plus_tier: true,
  },
  {
    id: 4,
    feature: "Access to Organizer Dashboard",
    free_tier_text: "Basic",
    pro_tier_text: "Advanced",
    pro_plus_tier_text: "Full + Analytics",
  },
  {
    id: 5,
    feature: "Early Access to New Features",
    free_tier_text: "-",
    pro_tier: true,
    pro_plus_tier: true,
    pro_plus_tier_text: "Priority Alerts",
  },
  {
    id: 6,
    feature: "Match Scheduling & Slotting Tool",
    free_tier_text: "Basic",
    pro_tier_text: "Advanced",
    pro_plus_tier_text: "Auto Slotting + Suggestions",
  },
  {
    id: 7,
    feature: "In-App Score Submission by Players",
    free_tier_text: "-",
    pro_tier: true,
    pro_plus_tier: true,
  },
  {
    id: 8,
    feature: "Auto Result Compilation & Leaderboards",
    free_tier_text: "-",
    pro_tier: true,
    pro_plus_tier: true,
  },
  {
    id: 9,
    feature: "Custom Branding (Event Posters)",
    free_tier_text: "-",
    pro_tier: true,
    pro_plus_tier: true,
  },
  {
    id: 10,
    feature: "Custom Branding (Event Posters)",
    free_tier_text: "-",
    pro_tier: true,
    pro_tier_text: "Template-based",
    pro_plus_tier: true,
    pro_plus_tier_text: "Fully Custom",
  },
  {
    id: 11,
    feature: "Withdrawal Fee",
    free_tier_text: "5%",
    pro_tier_text: "2%",
    pro_plus_tier_text: "0% – Full Payout",
  },
  {
    id: 12,
    feature: "Tournament Refund Management",
    free_tier_text: "Manual",
    pro_tier_text: "Assisted",
    pro_plus_tier_text: "Auto Refund/Slot Replacement",
  },
  {
    id: 13,
    feature: "Club & Academy Association",
    free_tier_text: "-",
    pro_tier: true,
    pro_plus_tier: true,
  },
  {
    id: 14,
    feature: "Featured in ‘Top Organizers’ on Homepage",
    free_tier_text: "-",
    pro_tier_text: "-",
    pro_plus_tier: true,
  },
  {
    id: 15,
    feature: "Support Access",
    free_tier_text: "Community",
    pro_tier_text: "Priority Email",
    pro_plus_tier_text: "Dedicated Manager",
  },
];

export const ClubPlanPricing = [
  {
    id: 1,
    name: "Small Club",
    members: "10-30",
    price: 999,
    free: "1 Free",
    features: ["Leaderboard", "Challenges", "Free Brackets for Known Formats"],
    color: "text-[#C9A900]",
    bg: "bg-[#C9A900]",
    premium: false,
  },
  {
    id: 2,
    name: "Medium Club",
    members: "30-64",
    price: 1199,
    free: "2 Free",
    features: [
      "Custom Brackets",
      "Yearly Data Retention",
      "+Small club Features",
    ],
    color: "text-[#9867FF]",
    bg: "bg-[#9867FF]",
    premium: false,
  },
  {
    id: 3,
    name: "Large Club",
    members: "64-200",
    price: 1499,
    free: "4 Free",
    features: [
      "AI-Powered Challenge Recommendation",
      "Event Promotion",
      "Social Media Integration",
    ],
    color: "text-[#6B66FA]",
    bg: "bg-[#6B66FA]",
    premium: true,
  },
  {
    id: 4,
    name: "Elite Club",
    members: "200-400",
    price: 1799,
    free: "6 Free",
    features: [
      "Priority Event Listings ",
      "Advanced Club Analytics",
      "+Large club Features",
    ],
    color: "text-[#E374FF]",
    bg: "bg-[#E374FF]",
    premium: false,
  },
  {
    id: 5,
    name: "Super Elite",
    members: "200+",
    price: 1999,
    free: "Unlimited",
    features: [
      "Featured Club Promotion",
      "AI-Powered Player & Team Insights",
      "Exclusive Growth Support",
    ],
    color: "text-[#4EF162]",
    bg: "bg-[#4EF162]",
    premium: false,
  },
];

export const PlayersPlanPricing = [
  {
    id: 1,
    price: 399,
    period: "3 Months",
    note: null,
    border: "border-[#C9A900]",
    color: "text-[#C9A900]",
  },
  {
    id: 2,
    price: 699,
    period: "6 Months",
    note: null,
    border: "border-[#9867FF]",
    color: "text-[#9867FF]",
  },
  {
    id: 3,
    price: 999,
    period: "12 Months",
    note: "Includes 50% off on first club membership!",
    border: "border-[#67CE63]",
    color: "text-[#67CE63]",
  },
];

export const TournamentPricing = [
  {
    id: 1,
    name: "Small Event",
    members: "30-60",
    price: 499,
    entry_fee: 250,
    per_player: 12.5,
    per_player_percentage: 5,
    color: "text-[#C9A900]",
  },
  {
    id: 2,
    name: "Medium Event",
    members: "60-150",
    price: 999,
    entry_fee: 250,
    per_player: 12.5,
    per_player_percentage: 5,
    color: "text-[#9867FF]",
  },
  {
    id: 3,
    name: "Large Event",
    members: "150-400",
    price: 2499,
    entry_fee: 500,
    per_player: 25,
    per_player_percentage: 5,
    color: "text-[#6B66FA]",
  },
  {
    id: 4,
    name: "Elite Event",
    members: "400+",
    price: 4999,
    entry_fee: 500,
    per_player: 25,
    per_player_percentage: 5,
    color: "text-[#C9A900]",
  },
];
