export type Organizer = {
  id: number;
  user_id: number;
  organization_email?: string;
  tier_status?: string;
  organization_name: string;
  organizer_name: string;
  mobile_number: string;
  document_url?: string;
  document_name?: string;
  organization_profile?: string;
  organization_role?: string;
  primary_sports: number[];
  verification_status?: string;
  other_sports: number[];
  state: string | null;
  city: string | null;
  stateId?: number | null;
  terms_and_condition_accepted: boolean;
  cityId?: number | null;
  social_links: string[];
  website_link: string;
  venue: string;
  pin: string;
  createdAt?: Date;
  updatedAt?: Date;
  organization_experience?: number;
  no_of_annual_events_hosted?: number;
};
